app:
  scheduler:
    enable: false
    interval: 15000
    force-check-delay: 15000
  database-access-type: jpa

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  github:
    defaultUrl: https://api.github.com
  stackoverflow:
    defaultUrl: https://api.stackexchange.com/2.3
  bot:
    defaultUrl: http://localhost:8090

springdoc:
  swagger-ui:
    path: /swagger-ui
