app:
  scheduler:
    enable: true
    interval: 5s
    force-check-delay: 5s

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  github:
    defaultUrl: https://api.github.com
  stackoverflow:
    defaultUrl: https://api.stackexchange.com/2.3
