app:
  scheduler:
    enable: false
    interval: 15000
    force-check-delay: 15000
  database-access-type: jpa
  useQueue: false
  kafka:
    bootstrap-servers: localhost:9092
    topicName: bot-updates

spring:
  liquibase:
    enabled: false
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  github:
    defaultUrl: https://api.github.com
    backoffType: CONSTANT
    retryCount: 3
    retryInterval: 1
    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  stackoverflow:
    defaultUrl: https://api.stackexchange.com/2.3
    backoffType: CONSTANT
    retryCount: 3
    retryInterval: 1
    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT
  bot:
    defaultUrl: http://localhost:8090
    backoffType: CONSTANT
    retryCount: 3
    retryInterval: 1
    statuses: INTERNAL_SERVER_ERROR, BAD_GATEWAY, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  queryCount: 15

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
      path-mapping:
        prometheus: metrics
      base-path: /
  metrics:
    tags:
      application: ${spring.application.name}
