global:
  scrape_interval: 10s

scrape_configs:
  - job_name: bot
    static_configs:
      - targets: ["host.docker.internal:8091"]

  - job_name: scrapper
    static_configs:
      - targets: ["host.docker.internal:8081"]
