app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  application:
    name: macbeth_link_tracker_bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

api:
  scrapper:
    defaultUrl: http://localhost:8080

springdoc:
  swagger-ui:
    path: /swagger-ui
