/*
 * This file is generated by jOOQ.
 */
package edu.java.api.domain.jooq.tables;


import edu.java.api.domain.jooq.DefaultSchema;
import edu.java.api.domain.jooq.Keys;
import edu.java.api.domain.jooq.tables.records.LinkChatJoinTableRecord;

import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LinkChatJoinTable extends TableImpl<LinkChatJoinTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>LINK_CHAT_JOIN_TABLE</code>
     */
    public static final LinkChatJoinTable LINK_CHAT_JOIN_TABLE = new LinkChatJoinTable();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<LinkChatJoinTableRecord> getRecordType() {
        return LinkChatJoinTableRecord.class;
    }

    /**
     * The column <code>LINK_CHAT_JOIN_TABLE.CHAT_ID</code>.
     */
    public final TableField<LinkChatJoinTableRecord, Long> CHAT_ID = createField(DSL.name("CHAT_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>LINK_CHAT_JOIN_TABLE.LINK_ID</code>.
     */
    public final TableField<LinkChatJoinTableRecord, Long> LINK_ID = createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    private LinkChatJoinTable(Name alias, Table<LinkChatJoinTableRecord> aliased) {
        this(alias, aliased, null);
    }

    private LinkChatJoinTable(Name alias, Table<LinkChatJoinTableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>LINK_CHAT_JOIN_TABLE</code> table reference
     */
    public LinkChatJoinTable(String alias) {
        this(DSL.name(alias), LINK_CHAT_JOIN_TABLE);
    }

    /**
     * Create an aliased <code>LINK_CHAT_JOIN_TABLE</code> table reference
     */
    public LinkChatJoinTable(Name alias) {
        this(alias, LINK_CHAT_JOIN_TABLE);
    }

    /**
     * Create a <code>LINK_CHAT_JOIN_TABLE</code> table reference
     */
    public LinkChatJoinTable() {
        this(DSL.name("LINK_CHAT_JOIN_TABLE"), null);
    }

    public <O extends Record> LinkChatJoinTable(Table<O> child, ForeignKey<O, LinkChatJoinTableRecord> key) {
        super(child, key, LINK_CHAT_JOIN_TABLE);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<LinkChatJoinTableRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_C;
    }

    @Override
    @NotNull
    public List<ForeignKey<LinkChatJoinTableRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_C8C, Keys.CONSTRAINT_C8);
    }

    private transient Chat _chat;
    private transient Link _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.CHAT</code> table.
     */
    public Chat chat() {
        if (_chat == null)
            _chat = new Chat(this, Keys.CONSTRAINT_C8C);

        return _chat;
    }

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public Link link() {
        if (_link == null)
            _link = new Link(this, Keys.CONSTRAINT_C8);

        return _link;
    }

    @Override
    @NotNull
    public LinkChatJoinTable as(String alias) {
        return new LinkChatJoinTable(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public LinkChatJoinTable as(Name alias) {
        return new LinkChatJoinTable(alias, this);
    }

    @Override
    @NotNull
    public LinkChatJoinTable as(Table<?> alias) {
        return new LinkChatJoinTable(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkChatJoinTable rename(String name) {
        return new LinkChatJoinTable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkChatJoinTable rename(Name name) {
        return new LinkChatJoinTable(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public LinkChatJoinTable rename(Table<?> name) {
        return new LinkChatJoinTable(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
