/*
 * This file is generated by jOOQ.
 */
package edu.java.api.domain.jooq;


import edu.java.api.domain.jooq.tables.Chat;
import edu.java.api.domain.jooq.tables.Link;
import edu.java.api.domain.jooq.tables.LinkChatJoinTable;
import edu.java.api.domain.jooq.tables.records.ChatRecord;
import edu.java.api.domain.jooq.tables.records.LinkChatJoinTableRecord;
import edu.java.api.domain.jooq.tables.records.LinkRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 = Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] { Chat.CHAT.CHAT_ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] { Link.LINK.LINK_ID }, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 = Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] { Link.LINK.URL }, true);
    public static final UniqueKey<LinkChatJoinTableRecord> CONSTRAINT_C = Internal.createUniqueKey(LinkChatJoinTable.LINK_CHAT_JOIN_TABLE, DSL.name("CONSTRAINT_C"), new TableField[] { LinkChatJoinTable.LINK_CHAT_JOIN_TABLE.CHAT_ID, LinkChatJoinTable.LINK_CHAT_JOIN_TABLE.LINK_ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<LinkChatJoinTableRecord, LinkRecord> CONSTRAINT_C8 = Internal.createForeignKey(LinkChatJoinTable.LINK_CHAT_JOIN_TABLE, DSL.name("CONSTRAINT_C8"), new TableField[] { LinkChatJoinTable.LINK_CHAT_JOIN_TABLE.LINK_ID }, Keys.CONSTRAINT_2, new TableField[] { Link.LINK.LINK_ID }, true);
    public static final ForeignKey<LinkChatJoinTableRecord, ChatRecord> CONSTRAINT_C8C = Internal.createForeignKey(LinkChatJoinTable.LINK_CHAT_JOIN_TABLE, DSL.name("CONSTRAINT_C8C"), new TableField[] { LinkChatJoinTable.LINK_CHAT_JOIN_TABLE.CHAT_ID }, Keys.CONSTRAINT_1, new TableField[] { Chat.CHAT.CHAT_ID }, true);
}
